$(document).ready(function(){
	$("#company").click(function(){
		$("label[for=company]").css("display","none");
	});
	$("#company").mouseleave(function(){
		$("label[for=company]").css("display","block");
	});
	$("#name").click(function(){
		$("label[for=name]").css("display","none");
	});
	$("#name").mouseleave(function(){
		$("label[for=name]").css("display","block");
	});
	$("#tel").click(function(){
		$("label[for=tel]").css("display","none");
	});
	$("#tel").mouseleave(function(){
		$("label[for=tel]").css("display","block");
	});
	$("#email").click(function(){
		$("label[for=email]").css("display","none");
	});
	$("#email").mouseleave(function(){
		$("label[for=email]").css("display","block");
	});
	$("#url").click(function(){
		$("label[for=url]").css("display","none");
	});
	$("#url").mouseleave(function(){
		$("label[for=url]").css("display","block");
	});
	$("#finance").click(function(){
		$("label[for=text]").css("display","none");
	});
	$("#finance").mouseleave(function(){
		$("label[for=text]").css("display","block");
	});
});
